# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker-compose" # See documentation for possible values
    directory: "/" # Location of package manifests
    update-types: version-update:semver-minor
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/featmap/"
    # Check for updates once a week
    schedule:
      interval: "monthly"
