services:
  traefik:
    image: traefik:v2
    container_name: traefik
    restart: always
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.mydnschallenge.acme.email=hvogel@hennevogel.de"
      - "--certificatesresolvers.mydnschallenge.acme.storage=acme.json"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=linodev4"
    ports:
      - 80:80
      - 443:443
    volumes:
      # expose docker socket to be able to listen to it
      - /var/run/docker.sock:/var/run/docker.sock:z
      # configuration file for ACME
      - ./traefik/acme.json:/etc/traefik/acme/acme.json:z
      - ./traefik/linode_dns_token.txt:/etc/linode_dns_token.txt:z
    environment:
      LINODE_TOKEN_FILE: /etc/linode_dns_token.txt
      LINODE_PROPAGATION_TIMEOUT: 300
  blog:
    image: tumbleweed_apache
    container_name: blog
    restart: always
    build:
      context: apache
      dockerfile: Dockerfile
    volumes:
      - ./blog/_site:/srv/www/htdocs:z
    labels:
      - traefik.enable=true
      - "traefik.http.routers.blog.rule=Host(`copyleft.dev`) || Host(`www.copyleft.dev`) || Host(`hennevogel.de`) || Host(`www.hennevogel.de`)"
      - traefik.http.routers.blog.entrypoints=websecure
      - traefik.http.routers.blog.tls.certresolver=mydnschallenge
      - traefik.http.middlewares.test-compress.compress=true
  thelounge:
    image: ghcr.io/thelounge/thelounge:4
    container_name: thelounge
    restart: always
    volumes:
      - ./thelounge/data:/var/opt/thelounge:z
    labels:    
      - traefik.enable=true
      - traefik.http.routers.thelounge.rule=Host(`irc.copyleft.dev`)
      - traefik.http.routers.thelounge.entrypoints=websecure
      - traefik.http.routers.thelounge.tls.certresolver=mydnschallenge
  featmap:
    image: leap_featmap
    container_name: featmap
    restart: always
    build:
      context: featmap
      dockerfile: Dockerfile
    volumes:
      - ./featmap/conf.json:/featmap/conf.json:z
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.featmap.rule=Host(`featmap.copyleft.dev`)
      - traefik.http.routers.featmap.entrypoints=websecure
      - traefik.http.routers.featmap.tls.certresolver=mydnschallenge
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:z
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
    environment:
      POSTGRES_DB: ${FEATMAP_DB_NAME}
      POSTGRES_USER: ${FEATMAP_DB_USER}
      POSTGRES_PASSWORD: ${FEATMAP_DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${FEATMAP_DB_USER} -d ${FEATMAP_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

